from setuptools import setup, find_packages

setup(
    name='ginmodelrepo',
    version='1.0.1',
    url='https://github.com/crim-ca/gin-model-repo.git',
    project_urls={
        "geoimagenet": "https://geoimagenet.ca",
        "thelper": "https://github.com/plstcharles/thelper",
    },
    author='CRIM',
    description='This is a deep learning model repository for the GeoImageNet project. '
                '(see details: https://github.com/crim-ca/geoimagenet)',
    maintainer='Francis Charette-Migneault',
    maintainer_email='francis.charette-migneault@crim.ca',
    contact='Samuel Foucher',
    contact_email='samuel.foucher@crim.ca',
    platforms=['linux_x86_64'],
    keywords=', '.join(['GeoImageNet', 'Models Zoo', 'Machine Learning', 'Classification', 'Segmentation']),
    classifiers=[
        'Development Status :: 4 - Beta',
        'Intended Audience :: Developers',
        'Intended Audience :: Science/Research',
        'License :: OSI Approved :: ISC License (ISCL)',
        'Natural Language :: English',
        'Operating System :: Unix',
        'Operating System :: POSIX',
        'Programming Language :: Python :: 3',
        'Programming Language :: Python :: 3.6',
        'Programming Language :: Python :: 3.7',
        'Programming Language :: Python :: 3.8',
        'Programming Language :: Python :: Implementation :: CPython',
        'Topic :: Scientific/Engineering :: Artificial Intelligence',
        'Topic :: Scientific/Engineering :: Image Recognition',
    ],
    packages=find_packages(),
    zip_safe=False,
    python_requires='>=3.6.*,<4',
    install_requires=[
        'googledrivedownloader==0.4',
        'numpy>=1.11.1',
        'matplotlib>=1.5.1',
        'pretrainedmodels==0.7.4',
        'six',
        # note: most dependencies that require special setup are handled by thelper (opencv, gdal)
        'thelper>=0.5',
        'torch',
        'torchvision>=0.6',
    ],
)
